feat(api): add BOBA price feeds
witnet/data-feed-app pull request #58
Opened 2021-08-19 09:32 UTC by Tommytrg

2021-08-31 17:05 UTC, mariocao reviewed
Is this PR still up to date?

2021-09-02 10:15 UTC, aesedepece requested changes

2021-09-02 10:15 UTC, aesedepece commented on packages/api/src/dataFeeds.json
> +    }
Not needed anymore

2021-09-02 10:15 UTC, aesedepece commented on packages/api/src/dataFeeds.json
> +    }
Same

2021-09-02 10:15 UTC, aesedepece commented on packages/api/src/dataFeeds.json
> +    "pollingPeriod": 5000,
This period is just too low

2021-09-09 10:06 UTC, Tommytrg commented
> Is this PR still up to date?

Indeed, I've updated and rebased the PR

2021-09-09 10:36 UTC, aesedepece reviewed
Looks OK to me but let's wait for the final addresses!

2021-09-09 15:30 UTC, aesedepece requested changes

2021-09-09 15:30 UTC, aesedepece commented on packages/api/src/dataFeeds.json
> +    "feedFullName": "boba-rinkeby_omg-btc_6",
```suggestion
    "feedFullName": "boba-rinkeby_omg-btc_9",
```

2021-09-14 15:31 UTC, merged

2021-09-14 15:32 UTC, aesedepece commented
Merged in af36b2fbb1826d03a4dadec6c7abb17cd58c540a